package paintbasico2d;

import java.awt.Dimension;
import sm.vpc.iu.Lienzo2DImagen;

/**
 *
 * @author Víctor Padi
 */
public class ventanaInterna extends javax.swing.JInternalFrame {
    MainWindow parent = null;
    
     public ventanaInterna(MainWindow p){
         parent = p;
         
         initComponents();
     }
    
    public ventanaInterna(MainWindow p, int w, int h) {
        parent = p;
        initComponents();
                
        this.setSize(new Dimension(w + 40, h + 50));


        lienzo.setPreferredSize(new Dimension(w, h));

    }
    
    public Lienzo2DImagen getLienzo(){
        return lienzo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScroll = new javax.swing.JScrollPane();
        panelFijo = new javax.swing.JPanel();
        lienzo = new sm.vpc.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelScroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelFijo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2));
        panelFijo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));

        lienzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzoMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        panelFijo.add(lienzo);

        panelScroll.setViewportView(panelFijo);

        getContentPane().add(panelScroll, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseMoved
        int[] px = null;
        
        px = this.lienzo.getImagen().getRaster().getPixel(evt.getX(), evt.getY(), px);
        
        if(px.length == 3)
            this.parent.setPosicionText("( X: " + evt.getX() + ", Y: " + evt.getY() + ") = [ " + px[0] + ", " + px[1] + ", " + px[2] + " ]");
        else if(px.length == 1)
            this.parent.setPosicionText("( X: " + evt.getX() + ", Y: " + evt.getY() + ") = [ " + px[0] + " ]");
    }//GEN-LAST:event_lienzoMouseMoved
       
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.vpc.iu.Lienzo2DImagen lienzo;
    private javax.swing.JPanel panelFijo;
    private javax.swing.JScrollPane panelScroll;
    // End of variables declaration//GEN-END:variables
}
