/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediatic;

/**
 * Dialogo que muestra la información relacionada a la aplicación.
 * @author Víctor Padilla
 */
public class SobreDialog extends javax.swing.JDialog {

    /**
     * Creates new form SobreDialog
     */
    public SobreDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setTitle("About me");
        
        chascarrilloLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appLabel = new javax.swing.JLabel();
        AutorLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        paraLabel = new javax.swing.JLabel();
        Yop = new javax.swing.JLabel();
        aceptarBoton = new javax.swing.JButton();
        chascarrilloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        appLabel.setText("Aplicación Creada por:");

        AutorLabel.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        AutorLabel.setText("Víctor Padilla Cabello");

        nombreLabel.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        nombreLabel.setText("MediaTic 1.0");
        nombreLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        paraLabel.setText("Para la asignatura Sistemas Multimedia");

        Yop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/me.jpg"))); // NOI18N
        Yop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Yop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YopMouseClicked(evt);
            }
        });

        aceptarBoton.setText("Aceptar");
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });

        chascarrilloLabel.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        chascarrilloLabel.setText("\"A mi no me mires, solo pasaba por aquí\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chascarrilloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptarBoton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Yop)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(paraLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(appLabel)))
                                .addContainerGap(49, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AutorLabel)
                                    .addComponent(nombreLabel))
                                .addGap(67, 67, 67))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombreLabel)
                .addGap(18, 18, 18)
                .addComponent(appLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AutorLabel)
                .addGap(18, 18, 18)
                .addComponent(paraLabel)
                .addGap(18, 18, 18)
                .addComponent(aceptarBoton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Yop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chascarrilloLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_aceptarBotonActionPerformed

    private void YopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YopMouseClicked
        Yop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cuidao.jpg"))); // NOI18N
        chascarrilloLabel.setVisible(true);
    }//GEN-LAST:event_YopMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutorLabel;
    private javax.swing.JLabel Yop;
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JLabel appLabel;
    private javax.swing.JLabel chascarrilloLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel paraLabel;
    // End of variables declaration//GEN-END:variables
}
