/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mediatic;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;

/**
 * Clase que hereda de VentanaInterna para mostrar la captura 
 * del vídeo de una webcam a traves de una JInternalFrame.
 * @author Víctor Padilla
 */
public class VentanaInternaCamara extends VentanaInterna {
    private Webcam camara = null;
    
    private VentanaInternaCamara(VentanaPrincipal p) {
        super(p);
        
        initComponents();
        
        this.setTitle("Webcam");

        camara = Webcam.getDefault();
        
        Dimension resoluciones[] = camara.getViewSizes();
        Dimension maxRes = resoluciones[resoluciones.length-1];

        camara.setViewSize(maxRes);
        
        if (camara != null) {
            WebcamPanel areaVisual = new WebcamPanel(camara);
            
            if (areaVisual!= null) {
                getContentPane().add(areaVisual, BorderLayout.CENTER);
                pack();
            }
        }
    }
    
    public static VentanaInternaCamara getInstance(VentanaPrincipal p){
        VentanaInternaCamara v = new VentanaInternaCamara(p);
    
        return (v.camara!=null?v:null);
    }
    
    public Webcam getCamera(){
        return camara;
    }
    
    public BufferedImage getFrame(){
        if(camara != null){
            return camara.getImage();
        }
        
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capturaPanel = new javax.swing.JPanel();
        capturaBoton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        capturaPanel.setRequestFocusEnabled(false);

        capturaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_add_a_photo_black_18dp.png"))); // NOI18N
        capturaBoton.setToolTipText("Realizar una captura");
        capturaBoton.setPreferredSize(new java.awt.Dimension(50, 40));
        capturaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturaBotonActionPerformed(evt);
            }
        });
        capturaPanel.add(capturaBoton);

        getContentPane().add(capturaPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if(camara != null){
            camara.close();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void capturaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturaBotonActionPerformed
        parent.crearVentanaCaptura(this.getFrame());
    }//GEN-LAST:event_capturaBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capturaBoton;
    private javax.swing.JPanel capturaPanel;
    // End of variables declaration//GEN-END:variables

}
