package mediatic;

/**
 * SuperClase que abarca a todas las formas de InternalFrame dentro 
 * de la VentanaPrincipal. Se crea esta clase para facilitar la gestión
 * de ventanas en el entorno de la aplicación.
 * @author Víctor Padilla
 */
public class VentanaInterna extends javax.swing.JInternalFrame {
    VentanaPrincipal parent = null;
    
    /**
     * Constructor que crea una VentanaInterna nueva y le asigna
     * asigna un componente padre (en este caso una VentanaPrincipal).
     */
    public VentanaInterna(VentanaPrincipal p) {
        parent = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
