/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.vpc.iu;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 * Clase para renderizar los elementos de un comboBox como botones de colores,
 * siempre que el modelo de datos sea del tipo Color.
 * @author Victor Padi
 */
public class ListCeldaColor extends javax.swing.JPanel implements ListCellRenderer{

    /**
     * Creates new form ListCeldaColor
     */
    public ListCeldaColor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorBoton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(colorBoton, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Component getListCellRendererComponent(JList jlist, Object value, int i, boolean bln, boolean bln1) {
        colorBoton.setBackground((Color) value);
        colorBoton.setForeground((Color) value);
        
        Dimension dim = new Dimension(20, 30);
        
        colorBoton.setPreferredSize(dim);
        
        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorBoton;
    // End of variables declaration//GEN-END:variables
}
